### ISSUE TITLE
Media downloading to-do list

### ISSUE THREAD

**Issue by Vexten** [Vexten/BallsBot-TG#4]
```[tasklist]
### Steps
- [ ] https://github.com/Vexten/BallsBot-TG/issues/1
- [ ] https://github.com/Vexten/BallsBot-TG/issues/3
- [ ] Create a subclass for general media downloads (direct link)
- [ ] Create subclasses for specific media downloads (Youtube, etc.)
- [ ] Create a class which controls which media downloader to use.
- [ ] Test all media downloading.
```
